// +build !ignore_autogenerated

//
// Copyright 2020 IBM Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertManagerConfig) DeepCopyInto(out *AlertManagerConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertManagerConfig.
func (in *AlertManagerConfig) DeepCopy() *AlertManagerConfig {
	if in == nil {
		return nil
	}
	out := new(AlertManagerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Certs) DeepCopyInto(out *Certs) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Certs.
func (in *Certs) DeepCopy() *Certs {
	if in == nil {
		return nil
	}
	out := new(Certs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmReleasesMonitor) DeepCopyInto(out *HelmReleasesMonitor) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmReleasesMonitor.
func (in *HelmReleasesMonitor) DeepCopy() *HelmReleasesMonitor {
	if in == nil {
		return nil
	}
	out := new(HelmReleasesMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IAMProvider) DeepCopyInto(out *IAMProvider) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IAMProvider.
func (in *IAMProvider) DeepCopy() *IAMProvider {
	if in == nil {
		return nil
	}
	out := new(IAMProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCMMonitor) DeepCopyInto(out *MCMMonitor) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCMMonitor.
func (in *MCMMonitor) DeepCopy() *MCMMonitor {
	if in == nil {
		return nil
	}
	out := new(MCMMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusConfig) DeepCopyInto(out *PrometheusConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	in.RouterResource.DeepCopyInto(&out.RouterResource)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusConfig.
func (in *PrometheusConfig) DeepCopy() *PrometheusConfig {
	if in == nil {
		return nil
	}
	out := new(PrometheusConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusExt) DeepCopyInto(out *PrometheusExt) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusExt.
func (in *PrometheusExt) DeepCopy() *PrometheusExt {
	if in == nil {
		return nil
	}
	out := new(PrometheusExt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrometheusExt) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusExtList) DeepCopyInto(out *PrometheusExtList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PrometheusExt, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusExtList.
func (in *PrometheusExtList) DeepCopy() *PrometheusExtList {
	if in == nil {
		return nil
	}
	out := new(PrometheusExtList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrometheusExtList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusExtSpec) DeepCopyInto(out *PrometheusExtSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.AlertManagerConfig.DeepCopyInto(&out.AlertManagerConfig)
	in.PrometheusConfig.DeepCopyInto(&out.PrometheusConfig)
	in.MCMMonitor.DeepCopyInto(&out.MCMMonitor)
	out.Certs = in.Certs
	out.IAMProvider = in.IAMProvider
	out.HelmReleasesMonitor = in.HelmReleasesMonitor
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusExtSpec.
func (in *PrometheusExtSpec) DeepCopy() *PrometheusExtSpec {
	if in == nil {
		return nil
	}
	out := new(PrometheusExtSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusExtStatus) DeepCopyInto(out *PrometheusExtStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusExtStatus.
func (in *PrometheusExtStatus) DeepCopy() *PrometheusExtStatus {
	if in == nil {
		return nil
	}
	out := new(PrometheusExtStatus)
	in.DeepCopyInto(out)
	return out
}
